name: 'Label to PullRequest when approved'
description: 'Label to PullRequest when approved'
inputs:
  GITHUB_TOKEN: # id of input
    description: 'github token'
    required: true
    default: 'None'
runs:
  using: 'node12'
  main: 'dist/index.js'
