name: 'Hello World'
description: 'Label to PullRequest'
inputs:
  MYTOKEN: # id of input
    description: 'github token'
    required: true
    default: 'None'
runs:
  using: 'node12'
  main: 'dist/index.js'
