on:
  - pull_request_review

jobs:
  label_job:
    runs-on: ubuntu-latest
    name: A job to Label to PullRequest when approved
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: npm ci
      - name: label action step
        uses: ./ # Uses an action in the root directory
        with:
          MYTOKEN: ${{ secrets.MYTOKEN }}
